### ISSUE TITLE
[CGCP] Migrate to DTO from raw conversion

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/inbound#68]
Currently, the conversion of data from API response takes place in raw format, that is, not regulated by DTO. We need to shift to DTOs to reinforce types.

After the changes are done, these things need to be tested out-

Flow Testing

- [ ] Bot Conversation Flow with Whatsapp Netcore (Working on)

Need to Test

- [ ] inbound:8085/campaign/start API

### Project
UCI

### Organization Name:
Samagra

### Domain                   
Communications

### Tech Skills Needed:
Java, SpringBoot

### Mentor(s)
@chinmoy12c 

### Complexity
Medium

### Category
Code Cleanup

### Sub Category
API, Backend, Technical Debt.

**Comment by KDwevedi** [comment]
comment

**Comment by rushi-02** [comment]
Can i work on this issue?

**Comment by Tanwika** [comment]
Hi, I would like to work on this issue.  
Hi @rushi-02 have you started working on this? Would like to know the baby steps you followed while setting up the project locally. Please share them here. 
PS: @chinmoy12c @KDwevedi

**Comment by SoumyadipYT-OSS** [comment]
Java and Spring Boot, which are essential for the project of migrating to DTO from raw conversion. This project is a challenging and rewarding one, as it will help me to improve the quality and efficiency of our software development process. Because of my skill set is matching with these criteria, I am interested in this project for gaining new real-world problem-solution.
